### ISSUE TITLE
IssueData

### ISSUE THREAD

**Issue by FDiskas** [fossapps/Handlebars-Issue-and-Pull-Requests#24]
Would be nice to have some variables about issue data. More info: https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls

Also there is ability in github to add custom issue link using https://github.com/fossapps/Handlebars-Issue-and-Pull-Requests/settings/key_links

Ir could be also included

**Comment by cyberhck** [comment]
Can you give an example of what you're looking for? Because it already has issue number using the {{id}}, it has user's data and labels.

What specific issueData are you looking for?

**Comment by FDiskas** [comment]
The main case is that our issues are remote not github issues. And to link them to remote server we are using https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls
Just wondering is it even possible to get that formatted link using github api or something

**Comment by cyberhck** [comment]
ahh, so when you write JIRA-1234 and you've set the custom linking, if that's what you mean, I haven't looked at payload more recently, also, I can't find it for any of my repositories yet, but if you can setup a repository with autolinked references setup, then install this app, I can try to debug by looking at what payload is sent. (just create a repo, install this app on that repo, enable autolink and test if autolink is actually working)

then let me know on this repo and I'll try it out.

**Comment by FDiskas** [comment]
I don't have github pro version only my customer. And I can't play around with their repo. Is it possible to deal something without doing so?

https://help.github.com/en/github/administering-a-repository/configuring-autolinks-to-reference-external-resources

**Comment by cyberhck** [comment]
not sure why I closed this, it must be by accident, I'll reopen,

I don't use pro either, if I get a chance, I'll try but this might take some time, just to investigate, once it's investigated only then I can tell you if it's possible or not.

**Comment by cyberhck** [comment]
I checked the other day, and issue payload doesn't have this info, which means if you want to do something with it, it'll have to be a new app :)
